### PR TITLE
feat(app): update typings and resolve previous router issues

### PR DESCRIPTION
**Pull request by Hotell**

### CODE REVIEW

**Comment by Hotell** [comment]
this should also remove any typescript 2.0 install issues you had @vire

**Comment by Hotell** [comment]
failing because https://github.com/s-panferov/awesome-typescript-loader/issues/224 maybe we should just stick with old good ts-loader wdyt?

**Comment by devopsmariocom** [comment]
hmmm... if `ts-loader` will fix the issue let's switch back.

I guess it's just single line change, so we can do some performance testing and decide which one is better later when things are more stable.

**Comment by Hotell** [comment]
Allright ts-loader doesn't work as well. It has another set of problem by loading Mocha definitions. huh. So I guess we will have to wait until that ats-loader bug is fixed

**Comment by devopsmariocom** [comment]
Do you have any idea what the real issue is inside of atl? Could downgrade help?

**Comment by Hotell** [comment]
can we merge now ? ;) @elmariofredo

**Comment by devopsmariocom** [comment]
LGTM

**Pull request merged**
